name: ✨ Request a feature
description: Request a new feature to implement in CardFoldr
title: "[Request] "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Please describe the problem the feature is supposed to solve.
      description: A clear and concise description of what the problem is. If it concerns a specific board game, please provide a link to it as well. Screenshots and other media also go a long way in helping to understand what you're talking about.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen. If you've considered alternatives, please describe them as well. Don't feel ashamed to include mockups either, no matter how they look!
    validations:
      required: true
